version: '3'

services:
  app:
    image: ambientum/php:8.1-nginx
    container_name: ignition-app
    volumes:
      - .:/var/www/app
      - ./docker/scripts:/scripts/entry.d
    ports:
      - 80:8080
      - 443:8083
    depends_on:
      - mysql

  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: ignition-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: ignition
      MYSQL_USER: ignition
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'mysql:/var/lib/mysql'

volumes:
  mysql:
    driver: local